/** Readable source for the Tradingskolan lesson. Patched into the Vite bundle. */

function compareTable(caption, headers, rows) {
  return "@table " + JSON.stringify({ caption, headers, rows });
}

export const lesson = {
  moduleId: "hopfield-minne",
  moduleTitle: "08 · Minne och mönsterigenkänning",
  moduleTitleEn: "08 · Memory and pattern recognition",
  moduleTitleUk: "08 · Пам'ять і розпізнавання образів",
  summary:
    "Hur Hopfields nätverk (1982) lagrar mönster som dalar i en energi, och hur en brusig ledtråd kan hämta hela mönstret — samma komplettering som gör att kända grafmönster kan dyka upp i brus.",
  summaryEn:
    "How Hopfield's network (1982) stores patterns as valleys in an energy, and how a noisy cue can retrieve the whole pattern — the same completion that lets familiar chart shapes show up in noise.",
  summaryUk:
    "Як мережа Гопфілда (1982) зберігає образи як долини енергії і як шумна підказка може відновити весь образ — те саме доповнення, через яке знайомі фігури графіка з'являються в шумі.",
  durationMinutes: 14,
  topics: ["Hopfield", "Hinton", "Symbolisk AI", "Hebb", "Minne", "Quiz"],
  topicsEn: ["Hopfield", "Hinton", "Symbolic AI", "Hebb", "Memory", "Quiz"],
  topicsUk: ["Гопфілд", "Гінтон", "Символьний ШІ", "Гебб", "Пам'ять", "Тест"],
  content: [
    "# Vad modellen är",
    "John Hopfield beskrev 1982 ett nätverk av binära neuroner. Varje neuron är antingen +1 eller −1. Varje par är kopplat med en symmetrisk vikt: vikten från i till j är samma som från j till i.",
    "Mönster lagras med Hebbs regel. För varje lagrat mönster x läggs produkten xᵢ · xⱼ till vikten wᵢⱼ. Summan går över alla mönster. Diagonalen är 0 — en neuron kopplas inte till sig själv. wᵢⱼ = Σ xᵢ·xⱼ.",
    "Återkallning uppdaterar en neuron i taget: sᵢ = sign(Σ wᵢⱼ·sⱼ). När summan är 0 behåller neuronen sitt tecken. När ingen neuron längre byter tecken är tillståndet stabilt.",
    "Energin E = −½ Σ wᵢⱼ sᵢ sⱼ sjunker vid varje steg som faktiskt ändrar en neuron. Nätverket rullar ner till närmaste dal. Den dalen är ett lagrat minne — eller, om nätet är överfullt, ett falskt minne.",
    "# Innehållsadresserat minne",
    "Du behöver inte en exakt adress. En ofullständig eller brusig ledtråd räcker för att hämta hela mönstret. Innehållet i ledtråden pekar ut minnet. Det kallas innehållsadresserat minne.",
    "# Begränsningar",
    "Kapaciteten är ungefär 0,14·N mönster för N neuroner. I demon är N = 100, alltså ungefär 14 mönster. Lagrar man fler blandas minnen. Det uppstår falska minnen (spurious states), till exempel blandningar av flera mönster och inverterade mönster.",
    "# Koppling till trading",
    "Hjärnan kompletterar mönster på liknande sätt. Det är nyttigt när en ofullständig bild ska bli en känd struktur. Samma mekanism gör att man kan se kända grafmönster i brus.",
    "Lärdom i utbildningen: kontrollera mönstret mot data och mot reglerna innan ett beslut.",
    "# Geoffrey Hinton",
    "Geoffrey Hinton byggde vidare på Hopfield-nätverket med Boltzmann-maskinen (1985, tillsammans med David Ackley och Terry Sejnowski). Neuronerna är stokastiska, och nätet har dolda enheter. Då lär sig nätverket känna igen och generera mönster i data, i stället för att bara lagra mönster som redan är givna.",
    "Han bidrog också till backpropagation, tillsammans med David Rumelhart och Ronald Williams (1986). Den metoden ligger bakom dagens djupinlärning.",
    "Hinton och Hopfield fick Nobelpriset i fysik 2024.",
    "I utbildningen gäller samma kontroll. Ett lärande system hittar mönster, men kan också överanpassa sig till brus. Kontrollera mönstret mot data innan ett beslut.",
    "# Symbolisk AI",
    "Symbolisk AI, också kallad GOFAI, arbetar med explicita regler och logik som människor skriver. Expertsystem och if-then-regler är exempel. Den är lätt att förklara, men skör när verkligheten avviker från reglerna.",
    "Nätverk i Hopfields och Hintons anda lär sig i stället mönster ur data. De tål brus, men är svårare att förklara.",
    "Neurosymbolisk AI kombinerar båda.",
    compareTable(
      "Symbolisk AI och nätverk",
      ["Egenskap", "Symbolisk AI (GOFAI)", "Nätverk (Hopfield/Hinton)"],
      [
        ["Arbetssätt", "Explicita regler och logik som människor skriver", "Lär sig mönster ur data"],
        ["Exempel", "Expertsystem, if-then-regler", "Hopfield-nätverk, Boltzmann-maskin"],
        ["Styrka", "Lätt att förklara", "Tål brus"],
        ["Gräns", "Skör när verkligheten avviker", "Svårare att förklara"],
      ],
    ),
    "I utbildningen ger mönsterigenkänning idén. Skrivna regler, till exempel en förbestämd stop-loss och storlek, kontrollerar den innan ett beslut.",
    "@quiet",
    "Tradingskolan ger adaptiva verktyg. Kunskapstestet låser upp nästa rekommenderade utbildningsmodul. Det är inte en licens eller ett certifikat, och det öppnar inte handel med riktiga medel.",
    "# Prova nätverket",
    "Rutnätet är 10×10 neuroner. Fyra enkla mönster är lagrade från början. Rita eller klicka, välj ett mönster, lägg på brus och tryck Återkalla. Energin visas medan tillståndet rullar ner. Knappen Lagra fler mönster fyller nätet över kapaciteten så att falska minnen kan visas.",
    "@hopfield",
    "# Källor",
    "Hopfield, J. J. (1982). Neural networks and physical systems with emergent collective computational abilities. Proceedings of the National Academy of Sciences.",
    "https://www.pnas.org/doi/10.1073/pnas.79.8.2554",
    "Nobelpriset i fysik 2024, pressmeddelande. John Hopfield tillsammans med Geoffrey Hinton.",
    "https://www.nobelprize.org/prizes/physics/2024/press-release/",
    "Geoffrey Hinton. Wikipedia.",
    "https://en.wikipedia.org/wiki/Geoffrey_Hinton",
    "Symbolisk AI. Wikipedia.",
    "https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence",
  ],
  contentEn: [
    "# What the model is",
    "In 1982 John Hopfield described a network of binary neurons. Each neuron is either +1 or −1. Every pair is joined by a symmetric weight: the weight from i to j equals the weight from j to i.",
    "Patterns are stored with Hebb's rule. For each stored pattern x, the product xᵢ · xⱼ is added to the weight wᵢⱼ. The sum runs over all patterns. The diagonal is 0 — a neuron is not tied to itself. wᵢⱼ = Σ xᵢ·xⱼ.",
    "Recall updates one neuron at a time: sᵢ = sign(Σ wᵢⱼ·sⱼ). When the sum is 0 the neuron keeps its sign. When no neuron changes sign any longer, the state is stable.",
    "The energy E = −½ Σ wᵢⱼ sᵢ sⱼ falls at every step that actually changes a neuron. The network rolls down into the nearest valley. That valley is a stored memory — or, if the net is overfull, a false memory.",
    "# Content-addressable memory",
    "You do not need an exact address. An incomplete or noisy cue is enough to retrieve the whole pattern. The content of the cue points to the memory. That is content-addressable memory.",
    "# Limits",
    "Capacity is about 0.14·N patterns for N neurons. In the demo N = 100, so about 14 patterns. Store more and memories mix. False memories appear (spurious states), for example blends of several patterns and inverted patterns.",
    "# Link to trading",
    "The brain completes patterns in a similar way. That is useful when an incomplete picture should become a known structure. The same mechanism lets you see familiar chart patterns in noise.",
    "Lesson for study: check the pattern against the data and against your rules before a decision.",
    "# Geoffrey Hinton",
    "Geoffrey Hinton built on the Hopfield network with the Boltzmann machine (1985, with David Ackley and Terry Sejnowski). The neurons are stochastic, and the net has hidden units. The network then learns to recognise and generate patterns in data, instead of only storing patterns that were already given.",
    "He also contributed to backpropagation, with David Rumelhart and Ronald Williams (1986). That method underlies today's deep learning.",
    "Hinton and Hopfield received the Nobel Prize in Physics 2024.",
    "The same check applies in study. A learning system finds patterns, but it can also overfit to noise. Check the pattern against the data before a decision.",
    "# Symbolic AI",
    "Symbolic AI, also called GOFAI, works with explicit rules and logic that people write. Expert systems and if-then rules are examples. It is easy to explain, but brittle when reality departs from the rules.",
    "Networks in the manner of Hopfield and Hinton instead learn patterns from data. They tolerate noise, but they are harder to explain.",
    "Neurosymbolic AI combines both.",
    compareTable(
      "Symbolic AI and networks",
      ["Property", "Symbolic AI (GOFAI)", "Networks (Hopfield/Hinton)"],
      [
        ["How it works", "Explicit rules and logic that people write", "Learns patterns from data"],
        ["Examples", "Expert systems, if-then rules", "Hopfield network, Boltzmann machine"],
        ["Strength", "Easy to explain", "Tolerates noise"],
        ["Limit", "Brittle when reality departs", "Harder to explain"],
      ],
    ),
    "In study, pattern recognition supplies the idea. Written rules, for example a predetermined stop-loss and size, check that idea before a decision.",
    "@quiet",
    "The trading school gives adaptive tools. The knowledge test unlocks the next recommended learning module. It is not a licence or a certificate, and it does not open trading with real money.",
    "# Try the network",
    "The grid is 10×10 neurons. Four simple patterns are stored at the start. Draw or click, pick a pattern, add noise and press Recall. Energy is shown while the state rolls downhill. The button Store more patterns fills the net past capacity so false memories can appear.",
    "@hopfield",
    "# Sources",
    "Hopfield, J. J. (1982). Neural networks and physical systems with emergent collective computational abilities. Proceedings of the National Academy of Sciences.",
    "https://www.pnas.org/doi/10.1073/pnas.79.8.2554",
    "The Nobel Prize in Physics 2024, press release. John Hopfield together with Geoffrey Hinton.",
    "https://www.nobelprize.org/prizes/physics/2024/press-release/",
    "Geoffrey Hinton. Wikipedia.",
    "https://en.wikipedia.org/wiki/Geoffrey_Hinton",
    "Symbolic AI. Wikipedia.",
    "https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence",
  ],
  contentUk: [
    "# Що це за модель",
    "1982 року Джон Гопфілд описав мережу бінарних нейронів. Кожен нейрон є або +1, або −1. Кожна пара з'єднана симетричною вагою: вага від i до j дорівнює вазі від j до i.",
    "Образи зберігаються за правилом Гебба. Для кожного збереженого образу x до ваги wᵢⱼ додається добуток xᵢ · xⱼ. Сума йде по всіх образах. Діагональ дорівнює 0 — нейрон не зв'язаний сам із собою. wᵢⱼ = Σ xᵢ·xⱼ.",
    "Відтворення оновлює один нейрон за раз: sᵢ = sign(Σ wᵢⱼ·sⱼ). Коли сума дорівнює 0, нейрон лишає свій знак. Коли жоден нейрон більше не змінює знак, стан стійкий.",
    "Енергія E = −½ Σ wᵢⱼ sᵢ sⱼ спадає на кожному кроці, який справді змінює нейрон. Мережа скочується в найближчу долину. Ця долина — збережена пам'ять або, якщо мережа переповнена, хибна пам'ять.",
    "# Пам'ять за вмістом",
    "Точна адреса не потрібна. Неповної або шумної підказки досить, щоб відновити весь образ. Вміст підказки вказує на пам'ять. Це пам'ять, адресована вмістом.",
    "# Межі",
    "Ємність — приблизно 0,14·N образів для N нейронів. У демо N = 100, тобто близько 14 образів. Якщо зберегти більше, спогади змішуються. З'являються хибні спогади (spurious states), наприклад суміші кількох образів та інвертовані образи.",
    "# Зв'язок із трейдингом",
    "Мозок доповнює образи схожим чином. Це корисно, коли неповна картина має стати відомою структурою. Той самий механізм змушує бачити знайомі фігури графіка в шумі.",
    "Висновок для навчання: перевірте образ за даними і за правилами перед рішенням.",
    "# Джеффрі Гінтон",
    "Джеффрі Гінтон розвинув мережу Гопфілда машиною Больцмана (1985, разом із Девідом Еклі та Террі Сейновським). Нейрони стохастичні, і мережа має приховані одиниці. Тоді мережа вчиться розпізнавати й породжувати образи в даних, а не лише зберігати вже задані образи.",
    "Він також долучився до backpropagation разом із Девідом Румельгартом і Рональдом Вільямсом (1986). Цей метод лежить в основі сучасного глибокого навчання.",
    "Гінтон і Гопфілд отримали Нобелівську премію з фізики 2024 року.",
    "У навчанні діє та сама перевірка. Система, що вчиться, знаходить образи, але може й перенавчитися на шум. Перевірте образ за даними перед рішенням.",
    "# Символьний ШІ",
    "Символьний ШІ, його також називають GOFAI, працює з явними правилами і логікою, які пишуть люди. Приклади — експертні системи та правила if-then. Його легко пояснити, але він крихкий, коли дійсність відхиляється від правил.",
    "Мережі в дусі Гопфілда і Гінтона натомість вчаться образів з даних. Вони терплять шум, але їх важче пояснити.",
    "Нейросимвольний ШІ поєднує обидва підходи.",
    compareTable(
      "Символьний ШІ і мережі",
      ["Властивість", "Символьний ШІ (GOFAI)", "Мережі (Гопфілд/Гінтон)"],
      [
        ["Як працює", "Явні правила і логіка, які пишуть люди", "Вчиться образів з даних"],
        ["Приклади", "Експертні системи, правила if-then", "Мережа Гопфілда, машина Больцмана"],
        ["Сила", "Легко пояснити", "Терпить шум"],
        ["Межа", "Крихкий, коли дійсність відхиляється", "Важче пояснити"],
      ],
    ),
    "У навчанні розпізнавання образів дає ідею. Написані правила, наприклад заздалегідь визначені stop-loss і розмір, перевіряють її перед рішенням.",
    "@quiet",
    "Торгова школа дає адаптивні інструменти. Перевірка знань відкриває наступний рекомендований навчальний модуль. Це не ліцензія і не сертифікат, і вона не відкриває торгівлю справжніми коштами.",
    "# Спробуйте мережу",
    "Сітка — 10×10 нейронів. На початку збережено чотири прості образи. Малюйте або натискайте, оберіть образ, додайте шум і натисніть «Відтворити». Енергія видно, поки стан скочується вниз. Кнопка «Зберегти більше образів» заповнює мережу понад ємність, щоб могли з'явитися хибні спогади.",
    "@hopfield",
    "# Джерела",
    "Hopfield, J. J. (1982). Neural networks and physical systems with emergent collective computational abilities. Proceedings of the National Academy of Sciences.",
    "https://www.pnas.org/doi/10.1073/pnas.79.8.2554",
    "Нобелівська премія з фізики 2024, пресреліз. Джон Гопфілд разом із Джеффрі Гінтоном.",
    "https://www.nobelprize.org/prizes/physics/2024/press-release/",
    "Джеффрі Гінтон. Wikipedia.",
    "https://en.wikipedia.org/wiki/Geoffrey_Hinton",
    "Символьний ШІ. Wikipedia.",
    "https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence",
  ],
  quiz: [
    {
      id: "hop-q1",
      prompt: "Vad är Hopfield-nätverket i den här lektionen?",
      promptEn: "What is the Hopfield network in this lesson?",
      promptUk: "Чим є мережа Гопфілда в цьому уроці?",
      explanation:
        "Neuronerna är binära (+1/−1), vikterna är symmetriska, och lagrade mönster är stabila tillstånd — dalar i energin.",
      explanationEn:
        "The neurons are binary (+1/−1), the weights are symmetric, and stored patterns are stable states — valleys in the energy.",
      explanationUk:
        "Нейрони бінарні (+1/−1), ваги симетричні, а збережені образи — стійкі стани, долини енергії.",
      options: [
        {
          id: "a",
          text: "En tabell där varje rad är en historisk kurs som ska memoreras exakt",
          textEn: "A table where each row is a historical price to memorise exactly",
          textUk: "Таблиця, де кожен рядок — історична ціна, яку треба запам'ятати точно",
          correct: false,
        },
        {
          id: "b",
          text: "Ett nät av binära neuroner (+1/−1) med symmetriska vikter, där mönster är stabila tillstånd",
          textEn: "A net of binary neurons (+1/−1) with symmetric weights, where patterns are stable states",
          textUk: "Мережа бінарних нейронів (+1/−1) із симетричними вагами, де образи — стійкі стани",
          correct: true,
        },
        {
          id: "c",
          text: "En licens som avslutar kursen",
          textEn: "A licence that finishes the course",
          textUk: "Ліцензія, яка завершує курс",
          correct: false,
        },
        {
          id: "d",
          text: "En slumpkoppling där bara en neuron styr alla andra",
          textEn: "A random wiring where only one neuron drives all the others",
          textUk: "Випадкове з'єднання, де лише один нейрон керує всіма іншими",
          correct: false,
        },
      ],
    },
    {
      id: "hop-q2",
      prompt: "Hur sätter Hebbs regel vikterna?",
      promptEn: "How does Hebb's rule set the weights?",
      promptUk: "Як правило Гебба задає ваги?",
      explanation: "wᵢⱼ är summan över mönster av xᵢ·xⱼ. Diagonalen, wᵢᵢ, är 0.",
      explanationEn: "wᵢⱼ is the sum over patterns of xᵢ·xⱼ. The diagonal, wᵢᵢ, is 0.",
      explanationUk: "wᵢⱼ — це сума по образах xᵢ·xⱼ. Діагональ, wᵢᵢ, дорівнює 0.",
      options: [
        {
          id: "a",
          text: "Varje vikt sätts till 1 mellan grannar i rutnätet och 0 annars",
          textEn: "Each weight is 1 between grid neighbours and 0 otherwise",
          textUk: "Кожна вага дорівнює 1 між сусідами в сітці і 0 в інших випадках",
          correct: false,
        },
        {
          id: "b",
          text: "Bara den första neuronen sparas, övriga vikter nollställs",
          textEn: "Only the first neuron is stored; the other weights are cleared",
          textUk: "Зберігається лише перший нейрон, решта ваг обнуляється",
          correct: false,
        },
        {
          id: "c",
          text: "wᵢⱼ är summan över mönster av xᵢ·xⱼ, och diagonalen är 0",
          textEn: "wᵢⱼ is the sum over patterns of xᵢ·xⱼ, and the diagonal is 0",
          textUk: "wᵢⱼ — сума по образах xᵢ·xⱼ, а діагональ дорівнює 0",
          correct: true,
        },
        {
          id: "d",
          text: "Vikten sätts efter hur grafen såg ut dagen efter",
          textEn: "The weight is set from how the chart looked the next day",
          textUk: "Вага ставиться за тим, як графік виглядав наступного дня",
          correct: false,
        },
      ],
    },
    {
      id: "hop-q3",
      prompt: "Vad menas med innehållsadresserat minne?",
      promptEn: "What does content-addressable memory mean?",
      promptUk: "Що означає пам'ять, адресована вмістом?",
      explanation:
        "En ofullständig eller brusig ledtråd räcker. Nätet kompletterar till hela det lagrade mönstret.",
      explanationEn:
        "An incomplete or noisy cue is enough. The net completes it to the whole stored pattern.",
      explanationUk:
        "Неповної або шумної підказки досить. Мережа доповнює її до цілого збереженого образу.",
      options: [
        {
          id: "a",
          text: "Mönstret kan bara hämtas med ett exakt indexnummer",
          textEn: "The pattern can be fetched only with an exact index number",
          textUk: "Образ можна дістати лише за точним номером індексу",
          correct: false,
        },
        {
          id: "b",
          text: "En ofullständig eller brusig ledtråd kan hämta hela mönstret",
          textEn: "An incomplete or noisy cue can retrieve the whole pattern",
          textUk: "Неповна або шумна підказка може відновити весь образ",
          correct: true,
        },
        {
          id: "c",
          text: "Ledtråden måste vara längre än själva mönstret",
          textEn: "The cue must be longer than the pattern itself",
          textUk: "Підказка має бути довшою за сам образ",
          correct: false,
        },
        {
          id: "d",
          text: "Brus gör att nätet alltid skapar ett mönster som aldrig lagrats",
          textEn: "Noise means the net always creates a pattern that was never stored",
          textUk: "Шум означає, що мережа завжди створює образ, який ніколи не зберігався",
          correct: false,
        },
      ],
    },
    {
      id: "hop-q4",
      prompt: "Vilken lärdom följer av kapaciteten och av falska minnen?",
      promptEn: "What follows from the capacity and from false memories?",
      promptUk: "Який висновок випливає з ємності та з хибних спогадів?",
      explanation:
        "Ungefär 0,14·N mönster ryms. Fler än så blandar minnen. Ett känt mönster i brus ska kontrolleras mot data och regler innan ett beslut. Testet för bara utbildningsvägen vidare.",
      explanationEn:
        "About 0.14·N patterns fit. More than that mixes memories. A familiar pattern in noise should be checked against data and rules before a decision. The test only moves the learning path forward.",
      explanationUk:
        "Вміщається приблизно 0,14·N образів. Більше — і спогади змішуються. Знайомий образ у шумі треба перевірити за даними і правилами перед рішенням. Тест лише просуває навчальний шлях.",
      options: [
        {
          id: "a",
          text: "Nätet kan lagra hur många mönster som helst utan att de blandas",
          textEn: "The net can store as many patterns as you like without mixing them",
          textUk: "Мережа може зберігати скільки завгодно образів без змішування",
          correct: false,
        },
        {
          id: "b",
          text: "Ett känt grafmönster i brus är i sig ett skäl att fatta beslutet",
          textEn: "A familiar chart pattern in noise is itself a reason to decide",
          textUk: "Знайома фігура графіка в шумі сама по собі є підставою для рішення",
          correct: false,
        },
        {
          id: "c",
          text: "Ungefär 0,14·N mönster ryms. För många blandar minnen. Kontrollera mönstret mot data och regler innan ett beslut",
          textEn: "About 0.14·N patterns fit. Too many mix memories. Check the pattern against data and rules before a decision",
          textUk: "Вміщається приблизно 0,14·N образів. Забагато — і спогади змішуються. Перевірте образ за даними і правилами перед рішенням",
          correct: true,
        },
        {
          id: "d",
          text: "Ett godkänt kunskapstest öppnar handel med riktiga medel",
          textEn: "A passed knowledge test opens trading with real money",
          textUk: "Складена перевірка знань відкриває торгівлю справжніми коштами",
          correct: false,
        },
      ],
    },
    {
      id: "hop-q5",
      prompt: "Vad tillförde Geoffrey Hinton efter Hopfield-nätverket, enligt lektionen?",
      promptEn: "What did Geoffrey Hinton add after the Hopfield network, according to this lesson?",
      promptUk: "Що Джеффрі Гінтон додав після мережі Гопфілда, згідно з уроком?",
      explanation:
        "Boltzmann-maskinen (1985, med Ackley och Sejnowski) har stokastiska neuroner och dolda enheter, så nätet lär sig känna igen och generera mönster i data. Hinton bidrog också till backpropagation (Rumelhart, Hinton, Williams 1986). Ett lärande system kan överanpassa sig till brus, så mönstret ska kontrolleras mot data.",
      explanationEn:
        "The Boltzmann machine (1985, with Ackley and Sejnowski) has stochastic neurons and hidden units, so the net learns to recognise and generate patterns in data. Hinton also contributed to backpropagation (Rumelhart, Hinton, Williams 1986). A learning system can overfit to noise, so the pattern should be checked against the data.",
      explanationUk:
        "Машина Больцмана (1985, з Еклі та Сейновським) має стохастичні нейрони й приховані одиниці, тож мережа вчиться розпізнавати й породжувати образи в даних. Гінтон також долучився до backpropagation (Rumelhart, Hinton, Williams 1986). Система, що вчиться, може перенавчитися на шум, тож образ треба перевірити за даними.",
      options: [
        {
          id: "a",
          text: "Boltzmann-maskinen lagrar bara färdiga mönster och har inga dolda enheter",
          textEn: "The Boltzmann machine only stores finished patterns and has no hidden units",
          textUk: "Машина Больцмана лише зберігає готові образи і не має прихованих одиниць",
          correct: false,
        },
        {
          id: "b",
          text: "Boltzmann-maskinen (1985, med Ackley och Sejnowski) har stokastiska neuroner och dolda enheter, så nätet lär sig känna igen och generera mönster. Hinton bidrog också till backpropagation (1986)",
          textEn: "The Boltzmann machine (1985, with Ackley and Sejnowski) has stochastic neurons and hidden units, so the net learns to recognise and generate patterns. Hinton also contributed to backpropagation (1986)",
          textUk: "Машина Больцмана (1985, з Еклі та Сейновським) має стохастичні нейрони й приховані одиниці, тож мережа вчиться розпізнавати й породжувати образи. Гінтон також долучився до backpropagation (1986)",
          correct: true,
        },
        {
          id: "c",
          text: "Backpropagation gör att ett mönster i brus inte behöver kontrolleras mot data",
          textEn: "Backpropagation means a pattern in noise need not be checked against the data",
          textUk: "Backpropagation означає, що образ у шумі не треба перевіряти за даними",
          correct: false,
        },
        {
          id: "d",
          text: "Hinton bytte ut neuronerna mot en lista med färdiga grafnamn",
          textEn: "Hinton replaced the neurons with a list of finished chart names",
          textUk: "Гінтон замінив нейрони списком готових назв графіків",
          correct: false,
        },
      ],
    },
    {
      id: "hop-q6",
      prompt: "Hur skiljer sig symbolisk AI från nätverk som Hopfields och Hintons, enligt lektionen?",
      promptEn: "How does symbolic AI differ from networks such as Hopfield's and Hinton's, according to this lesson?",
      promptUk: "Чим символьний ШІ відрізняється від мереж на кшталт Гопфілда і Гінтона, згідно з уроком?",
      explanation:
        "Symbolisk AI (GOFAI) arbetar med explicita regler och logik som människor skriver. Nätverken lär sig mönster ur data. Neurosymbolisk AI kombinerar båda. I utbildningen ger mönsterigenkänning idén, och skrivna regler, till exempel en förbestämd stop-loss och storlek, kontrollerar den innan ett beslut.",
      explanationEn:
        "Symbolic AI (GOFAI) works with explicit rules and logic that people write. The networks learn patterns from data. Neurosymbolic AI combines both. In study, pattern recognition supplies the idea, and written rules, for example a predetermined stop-loss and size, check it before a decision.",
      explanationUk:
        "Символьний ШІ (GOFAI) працює з явними правилами і логікою, які пишуть люди. Мережі вчаться образів з даних. Нейросимвольний ШІ поєднує обидва підходи. У навчанні розпізнавання образів дає ідею, а написані правила, наприклад заздалегідь визначені stop-loss і розмір, перевіряють її перед рішенням.",
      options: [
        {
          id: "a",
          text: "Symbolisk AI lär sig mönster ur data och tål brus bättre än skrivna regler",
          textEn: "Symbolic AI learns patterns from data and tolerates noise better than written rules",
          textUk: "Символьний ШІ вчиться образів з даних і терпить шум краще за написані правила",
          correct: false,
        },
        {
          id: "b",
          text: "Symbolisk AI använder explicita regler som människor skriver. Den är lätt att förklara men skör. Nätverken lär sig mönster ur data och tål brus, men är svårare att förklara",
          textEn: "Symbolic AI uses explicit rules that people write. It is easy to explain but brittle. The networks learn patterns from data and tolerate noise, but they are harder to explain",
          textUk: "Символьний ШІ використовує явні правила, які пишуть люди. Його легко пояснити, але він крихкий. Мережі вчаться образів з даних і терплять шум, але їх важче пояснити",
          correct: true,
        },
        {
          id: "c",
          text: "Nätverk är if-then-regler som människor skriver, och de är sköra när verkligheten avviker",
          textEn: "Networks are if-then rules that people write, and they are brittle when reality departs",
          textUk: "Мережі — це правила if-then, які пишуть люди, і вони крихкі, коли дійсність відхиляється",
          correct: false,
        },
        {
          id: "d",
          text: "Mönsterigenkänning räcker som beslut. Skrivna regler som stop-loss behövs inte",
          textEn: "Pattern recognition is enough as a decision. Written rules such as a stop-loss are not needed",
          textUk: "Розпізнавання образів достатньо як рішення. Написані правила, як-от stop-loss, не потрібні",
          correct: false,
        },
      ],
    },
  ],
  relatedLinks: [
    {
      to: "https://www.pnas.org/doi/10.1073/pnas.79.8.2554",
      external: true,
      labelSv: "Hopfield 1982, PNAS",
      labelEn: "Hopfield 1982, PNAS",
      labelUk: "Гопфілд 1982, PNAS",
      descriptionSv: "Neural networks and physical systems with emergent collective computational abilities.",
      descriptionEn: "Neural networks and physical systems with emergent collective computational abilities.",
      descriptionUk: "Neural networks and physical systems with emergent collective computational abilities.",
    },
    {
      to: "https://www.nobelprize.org/prizes/physics/2024/press-release/",
      external: true,
      labelSv: "Nobelpriset i fysik 2024",
      labelEn: "Nobel Prize in Physics 2024",
      labelUk: "Нобелівська премія з фізики 2024",
      descriptionSv: "Pressmeddelande: John Hopfield tillsammans med Geoffrey Hinton.",
      descriptionEn: "Press release: John Hopfield together with Geoffrey Hinton.",
      descriptionUk: "Пресреліз: Джон Гопфілд разом із Джеффрі Гінтоном.",
    },
    {
      to: "https://en.wikipedia.org/wiki/Geoffrey_Hinton",
      external: true,
      labelSv: "Geoffrey Hinton, Wikipedia",
      labelEn: "Geoffrey Hinton, Wikipedia",
      labelUk: "Джеффрі Гінтон, Wikipedia",
      descriptionSv: "Boltzmann-maskinen, backpropagation och Nobelpriset i fysik 2024.",
      descriptionEn: "The Boltzmann machine, backpropagation and the Nobel Prize in Physics 2024.",
      descriptionUk: "Машина Больцмана, backpropagation і Нобелівська премія з фізики 2024.",
    },
    {
      to: "https://en.wikipedia.org/wiki/Symbolic_artificial_intelligence",
      external: true,
      labelSv: "Symbolisk AI, Wikipedia",
      labelEn: "Symbolic AI, Wikipedia",
      labelUk: "Символьний ШІ, Wikipedia",
      descriptionSv: "Explicita regler och logik, som kontrast till nätverk som lär sig mönster ur data.",
      descriptionEn: "Explicit rules and logic, as a contrast to networks that learn patterns from data.",
      descriptionUk: "Явні правила і логіка, як контраст до мереж, що вчаться образів з даних.",
    },
    {
      to: "/nyheter/2026-09-28/tyst-tid/",
      external: true,
      labelSv: "Tyst tid före beslut",
      labelEn: "Quiet time before a decision",
      labelUk: "Тиша перед рішенням",
      descriptionSv: "Pausen innan ett beslut: lägg ifrån dig bruset och se vad som faktiskt ligger framför dig.",
      descriptionEn: "The pause before a decision: set the noise aside and look at what is actually in front of you.",
      descriptionUk: "Пауза перед рішенням: відкладіть шум і подивіться, що насправді перед вами.",
    },
  ],
};

export const pathStep = {
  id: "path-hopfield",
  courseId: "trading-grund",
  moduleId: "hopfield-minne",
  labelSv: "18 · Minne och mönster",
  labelEn: "18 · Memory and patterns",
  labelUk: "18 · Пам'ять і образи",
  whySv: "En brusig ledtråd kan se ut som ett känt mönster. Kontrollera mot data och regler innan ett beslut.",
  whyEn: "A noisy cue can look like a familiar pattern. Check it against data and rules before a decision.",
  whyUk: "Шумна підказка може виглядати як знайомий образ. Перевірте її за даними і правилами перед рішенням.",
  phase: "advanced",
};
